Move modules into proper folder structure and rename to proper names
PermaNulled/cartographer pull request #418
Opened 2023-03-25 01:28 UTC by Berthalamew

- try and organize some of the Engine related code we have into the Blam/Engine folder instead 
- rename some structs so that they parody the original struct names
- move some of the structs/definitions to proper modules

2023-03-25 01:30 UTC, Kantanomo commented
Waiting for appvayor.

2023-03-25 01:31 UTC, Kantanomo commented on xlive/Blam/Engine/Simulation/SimulationWorld.h
player_action is not just used for Simulation world, it's used for player control globals. should remain outside of it.

2023-03-25 01:32 UTC, Kantanomo commented on xlive/Blam/Engine/cache/cache_files.h
Explain the need for this change.

2023-03-25 01:35 UTC, Kantanomo commented on xlive/Blam/Engine/game/players.h
Might be fine but it might be better to put them into a Local players structure, local players contains more information. unsure though

2023-03-25 01:36 UTC, Berthalamew commented on xlive/Blam/Engine/cache/cache_files.h
it's the module where the tag iterator should be located in. (if there's a better spot let me know)

2023-03-25 01:37 UTC, Kantanomo commented on xlive/Blam/Engine/memory/data.h
i'd prefer data_array unsure though

2023-03-25 01:38 UTC, Berthalamew commented on xlive/Blam/Engine/Simulation/SimulationWorld.h
changed

2023-03-25 01:39 UTC, Kantanomo requested changes
Address the comments please, there are some changes that need to be modified and other things need to be explained or reasoned for.

2023-03-25 01:41 UTC, Kantanomo commented on xlive/Blam/Engine/cache/cache_files.h
why name it cache_files when tag data iterator is also usable inside the memory.

2023-03-25 01:43 UTC, Kantanomo commented on xlive/Blam/Engine/game/players.h
they do resolve to the game state player object but would we rather want for example... local_player(1)->get_gamestaete or game_state->get_local_player(1)

2023-03-25 01:43 UTC, Berthalamew commented on xlive/Blam/Engine/cache/cache_files.h
Since that's where the tag files are being loaded from

2023-03-25 01:48 UTC, Kantanomo commented
Changes are purely organizational (renaming, relocating) for easier navigation should not cause any issues in project however the specifics of things moved around should have minimal testing to make sure things still function as they should @Berthalamew .

2023-03-25 01:49 UTC, Berthalamew commented on xlive/Blam/Engine/game/players.h
Local players should be similar enough to players although you're right about extra data at the end. Depending on how different and how much extra data there is it could be fine to just make it a separate module. 
For now it should be fine to keep it within players?

2023-03-25 01:55 UTC, Berthalamew commented on xlive/Blam/Engine/memory/data.h
data_array is just one part of it and there's other functions in that module that use the data_array for allocating memory

2023-03-25 10:31 UTC, nukeulater commented
also https://github.com/pnill/cartographer/pull/413#issuecomment-1467589003

2023-03-25 22:56 UTC, Berthalamew commented on xlive/Blam/Engine/game/players.h
created the module for local_players

2023-03-26 01:37 UTC, Kantanomo approved these changes

2023-03-26 01:37 UTC, Kantanomo commented
Write a detailed description of the changes and how they will be beneficial to the project and merge it in with that as the comment.,

2023-03-26 01:48 UTC, Berthalamew commented
Organize some of the Engine related code we have into the Blam/Engine folder and rename the modules to their original counterparts.
This is beneficial since it keeps everything organized and tries to parody the original source layout of halo 2.

2023-03-26 01:50 UTC, merged