draw_string & main_render.cpp hook
PermaNulled/cartographer pull request #510
Opened 2023-12-29 23:41 UTC by punpckhdq

this pr obliterates the d3d9x game and update status text renderer as well as the achievement renderer.
in their place i patch a nullsub call in render_frame after all other game rendering has concluded. i use the game's draw_string functionality to render text there.
the position rendering code in XLiveRendering has been commented out. i don't know whether people care about that and neither do i know if it should be rendered in imgui or native.

2023-12-30 00:57 UTC, Kantanomo commented on xlive/Blam/Engine/main/main_render.cpp
> +	PatchCall(Memory::GetAddress(0x19228E), main_render_hook);
Can you add a comment that this is replacing a null sub

2023-12-31 00:21 UTC, Berthalamew requested changes

2023-12-31 00:21 UTC, Berthalamew commented on xlive/Blam/Engine/render/render_cartographer_ingame_ui.cpp
> +	real_argb_color text_color_console = **Memory::GetAddress<real_argb_color**>(0x41277C);
add global_real_argb_white to color_math instead of grabbing the address here

2023-12-31 00:21 UTC, Berthalamew commented on xlive/Blam/Engine/render/render_cartographer_ingame_ui.cpp
> +			real_argb_color text_color = **Memory::GetAddress<real_argb_color**>(0x41277C);
add global_real_argb_white to color_math instead of grabbing the address here

2023-12-31 00:21 UTC, Berthalamew commented on xlive/Blam/Engine/render/render_cartographer_ingame_ui.cpp
> +		draw_string_set_font_and_options(k_update_status_font, 0, 0, 0, *Memory::GetAddress<real_argb_color**>(0x41277C), *Memory::GetAddress<real_argb_color**>(0x412780), false);
add global_real_argb_white to color_math instead of grabbing the address here

2023-12-31 07:43 UTC, merged