fix crosshair scaling
PermaNulled/cartographer pull request #739
Opened 2024-11-09 22:43 UTC by Kantanomo

2024-11-09 23:02 UTC, Berthalamew requested changes

2024-11-09 23:02 UTC, Berthalamew commented on xlive/H2MOD.cpp
> +	hud_draw_on_map_load();
We don't need to do this on dedis

2024-11-10 00:02 UTC, Kantanomo commented on xlive/H2MOD.cpp
> +	hud_draw_on_map_load();
fixed

2024-11-10 00:06 UTC, Berthalamew requested changes

2024-11-10 00:06 UTC, Berthalamew commented on xlive/Blam/Engine/interface/new_hud_draw.cpp
> +		free(g_draw_hud_crosshair_bitmap_cache);
g_draw_hud_crosshair_bitmap_cache should also be freed when we close the game, not just here

2024-11-10 00:35 UTC, merged